### PR TITLE
UTC-176-C32 Adding lowercase double thorn/wynn

### PR DESCRIPTION
**Pull request by macchiati**
Adding 2 characters (listed in the doc as the following but only the capitals are new)
```
A7D2;LATIN CAPITAL LETTER DOUBLE THORN;Ll;0;L;;;;;N;;;;A7D3;
A7D3;LATIN SMALL LETTER DOUBLE THORN;Ll;0;L;;;;;N;;;A7D2;;A7D2
A7D4;LATIN CAPITAL LETTER DOUBLE WYNN;Ll;0;L;;;;;N;;;;A7D5;
A7D5;LATIN SMALL LETTER DOUBLE WYNN;Ll;0;L;;;;;N;;;A7D4;;A7D4
```

### CODE REVIEW

**Comment by macchiati** [comment]
In second pass, fix LineBreak

**Comment by macchiati** [comment]
Note: files were also generated in /extra/ and /cldr/. I didn't include those.

**Comment by macchiati** [comment]
I changed XX to AL in LineBreak.txt, and regenerated with MakeUnicodeFiles. However, in the generated LineBreak.txt file, it reverted the change.

**Comment by macchiati** [comment]
Some errors still:

Error:    TestProperties>TestFmwkMinusMinus.tearDown:23 errln()
Missing Common unexpected: [꟒꟔]
Missing Common[]!=[꟒꟔] ==> expected: <0> but was: <2>
Error:    TestTestUnicodeInvariants.testUnicodeInvariants:35 TestUnicodeInvariants.testInvariants() failed ==> expected: <0> but was: <1>

**Review by nedley — APPROVED** [review]

**Comment by markusicu** [comment]
No, wait, this is bad -- these characters are only *provisionally assigned*. **They are not approved for Unicode 16.0.**

The task was to review the proposal and prepare a pull request, but we must not *merge* post-16 pull requests into the `main` branch until the characters are approved for a version and the main branch is open for that version.

**We need to either revert this PR or urgently ask SAH+RMG+UTC to approve these characters for 16.**
@macchiati @nedley @Ken-Whistler @dwanders-A @PeterConstable

**Comment by markusicu** [comment]
By the way, the PR title is wrong, this is adding the capital letters not the lowercase ones.

RMG tracking issue:
- https://github.com/unicode-org/utc-release-management/issues/54

**Comment by roozbehp** [comment]
Let's revert this. "We accidentally merged this" is not a good-enough reason for moving them to 16.0.

**Comment by Ken-Whistler** [comment]
I agree with Roozbeh. This has to be reverted, and folks need to make sure they pay attention to the status in the actual pipeline before premature merging to main for a release. The process of trying to get ahead on the property development and to break up the property development into individual pull requests needs to be disciplined, so it doesn't actually interfere with the release cycle and getting to closure.

**Comment by markusicu** [comment]
> I agree with Roozbeh. This has to be reverted,

Revert pull request: https://github.com/unicode-org/unicodetools/pull/628

> and folks need to make sure they pay attention to the status in the actual pipeline before premature merging to main for a release.

Yes, both authors and reviewers... Pull requests for provisionally assigned characters should be *draft* pull requests until their characters/scripts are approved, and until `main` is open for the relevant version of Unicode.

**Comment by markusicu** [comment]
Reverted.

**Comment by nedley** [comment]
> Yes, both authors and reviewers...

I love how this is now my fault.

**Comment by macchiati** [comment]
My fault, sorry.

Need also to add this to the instructions, as it wasn't visible.

**Comment by eggrobin** [comment]
> Need also to add this to the instructions, as it wasn't visible.

Indeed I did not have « make it a draft PR », but the following instructions that are there [in the checklist](https://github.com/unicode-org/unicodetools/blob/main/docs/pipeline.md#checklist) were missed:

> Proposal document — Cite L2 number
> UTC decisions — Cite in extenso
> data-for-new — Set label
> pipeline-* — Set label

Trying to think about how we could avoid making that kind of mistake again:
- It should be possible to have some automation that prevents something labelled as pipeline-provisionally-assigned from being merged, but that won’t help if it isn’t labelled.
- I guess we could require any PR that touches UnicodeData.txt to be appropriately labelled.

I’ll play with GitHub workflows a bit and see if I can make that happen.

**Comment by macchiati** [comment]
Thanks, I like having the tooling enforce the process, where that is not
too onerous; prevents people like me from making dumb errors.

**Pull request merged**
