### PR TITLE
Update to CLDR version that includes jar sources

### PR DESCRIPTION
**Pull request by srl295**
- per CLDR-15195
- Now updates to CLDR version 0.0.0-SNAPSHOT-472af8d773
- CLDR release: snapshot/2022-01-10
- https://github.com/unicode-org/cldr/releases/tag/snapshot%2F2022-01-10

### CODE REVIEW

**Comment by srl295** [comment]
```
org.unicode.cldr.util.SimpleFactory$NoSourceDirectoryException: Unable to determine the source directory for locale ks_Deva
	at org.unicode.test.TestSecurity.TestCldrConsistency(TestSecurity.java:232)
```

I'll check locally to see what broke.

**Comment by srl295** [comment]
> ```
> org.unicode.cldr.util.SimpleFactory$NoSourceDirectoryException: Unable to determine the source directory for locale ks_Deva
> 	at org.unicode.test.TestSecurity.TestCldrConsistency(TestSecurity.java:232)
> ```
> 
> 
>      
>   
> 
> I'll check locally to see what broke.

I didn't check this, and I'm not sure if it's related. Looks like it may have broken again.

**Comment by srl295** [comment]
ks_Deva is in seed, so need to use the full factory

**Comment by srl295** [comment]
@Manishearth  try this locally also

**Comment by Manishearth** [comment]
This works!

**Comment by srl295** [comment]
> This works!

Still failing in CI.  :/ i might actually git bisect it. see if i can figure out what change broke.

**Comment by srl295** [comment]
@markusicu  @Manishearth  please review and merge… to unblock

**Review by Manishearth — APPROVED** [review]

**Review by markusicu — APPROVED** [review]
rslgtm

**Pull request merged**
