### PR TITLE
Reorder several new emoji based on ESC feedback

### PR DESCRIPTION
**Pull request by nedley**
Corresponding to https://github.com/unicode-org/emoji/pull/26

### CODE REVIEW

**Comment by nedley** [comment]
@macchiati I will be out the rest of this week, if there is urgency in conveying this to CLDR could you help out?

**Review by macchiati — APPROVED** [review]
Thanks! Once this is in, let me know so we can update the CLDR data. (We'll need a regenerated emoji-test file.)

**Comment by nedley** [comment]
emoji-test.txt and not something like emoji-ordering-rules.txt? If the latter, it has already been committed the emoji repo. If the former, I can rebuild and repost once I’m back from vacation next week.

**Comment by josh-hadley** [comment]
@nedley when you're ready please Squash and merge

**Comment by macchiati** [comment]
It uses the emoji-test file plus the ordering rules. The former gives cldr
the category information, while the latter provides the ordering.

**Comment by nedley** [comment]
> Okay, feel free to take whatever you need.

Ah, I guess you still need a new emoji-text.txt? Will get that in shortly, sorry for my poor reading comprehension.

**Comment by macchiati** [comment]
NP

**Comment by nedley** [comment]
@markusicu One might ask the same about your question. ;)

**Pull request merged**
