### PR TITLE
deps: bump cldr to v41, drop xerces

### PR DESCRIPTION
**Pull request by srl295**
For: #218

### CODE REVIEW

**Comment by srl295** [comment]
sorry for the delay, see if this works.

**Comment by echeran** [comment]
Even though this looks like the right change, it didn't make a difference...I'm trying to get Eclipse to import the project without errors, but it still complains about a module conflict for the `org.xml.sax.*` import statements.  (It says the org.xml.sax package is accessible from more than one module: <unnamed>, java.xml).

That error sounds like an error that you may have encountered in CLDR and solved through some of these changes. If so, was there anything else (ex: any other configs somewhere) to solve this problem?

**Review by markusicu — APPROVED** [review]
changes lgtm

I haven't tried to patch these in. Given that these changes are equivalent to those in CLDR, maybe just merge, and we update Eclipse and see?

**Comment by markusicu** [comment]
... and thanks for jumping on this!

**Comment by markusicu** [comment]
Looks like the core problem is that the imports fail with the well-known "The package org.xml.sax is accessible from more than one module: `<unnamed>`, java.xml"

**Comment by markusicu** [comment]
unicodetools > Properties > Java Build Path > Classpath / Maven Dependencies still lists xercesImpl

I can't edit it, but this item points to ~/.m2/repository/xerces/xercesImpl/2.12.0/ on my machine.

I shouldn't have to blow that folder away, right? The Maven project should just stop referring to it?
(I am afraid some other Java project might still need it; ICU?)

**Comment by srl295** [comment]
@markusicu  I'm testing on Eclipse now instead of just maven.

**Comment by srl295** [comment]
@markusicu  I found the problem. This is v41, yes, but the JDK11 and CLDR fixes for eclipse landed in v42.

I'm testing a snapshot of  cldr `v42` now https://github.com/unicode-org/cldr/releases/tag/snapshot%2F2022-04-25

**Pull request merged**
