### PR TITLE
Ten Chemical Symbols

### PR DESCRIPTION
**Pull request by eggrobin**
UTC-177-C33: Consensus: Provisionally assign the following 10 code points for chemical symbols, based on [L2/23-193R2](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/23-193R2):

	2B96 MEDIUM SMALL WHITE CIRCLE WITH HORIZONTAL BAR
	1F8D0 LONG RIGHTWARDS ARROW OVER LONG LEFTWARDS ARROW
	1F8D1 LONG RIGHTWARDS HARPOON OVER LONG LEFTWARDS HARPOON
	1F8D2 LONG RIGHTWARDS HARPOON ABOVE SHORT LEFTWARDS HARPOON
	1F8D3 SHORT RIGHTWARDS HARPOON ABOVE LONG LEFTWARDS HARPOON
	1F8D4 LONG LEFTWARDS HARPOON ABOVE SHORT RIGHTWARDS HARPOON
	1F8D5 SHORT LEFTWARDS HARPOON ABOVE LONG RIGHTWARDS HARPOON
	1F8D6 LONG RIGHTWARDS ARROW WITH THROUGH X
	1F8D7 LONG RIGHTWARDS ARROW WITH DOUBLE SLASH
	1F8D8 LONG LEFT RIGHT ARROW WITH DEPENDENT LOBE

* https://github.com/unicode-org/sah/issues/323
* https://github.com/unicode-org/utc-release-management/issues/62

UTC-178-C1 Consensus: Correct the name of the provisionally assigned U+1F8D6 LONG RIGHTWARDS ARROW WITH THROUGH X to LONG RIGHTWARDS ARROW THROUGH X . (Ref. L2/24-008)

UTC-178-C32 Consensus: Change the provisional code point for MEDIUM SMALL WHITE CIRCLE WITH HORIZONTAL BAR from U+2B96 (cf. Consensus UTC-177-C33) to U+1CEF0.

[[181-C60](https://www.unicode.org/cgi-bin/GetL2Ref.pl?181-C60)] Consensus: UTC accepts for encoding in Unicode Version 17.0 the following 297 Arabic, Bengali, Han, Kannada, Latin, Oriya, phonetic, Sharada, Tangut, Telugu, and symbol characters for which the code points have previously been provisionally assigned:

        Arabic (40 characters): 088F, FBC3..FBD2, FD90..FD91, FDC8..FDCE, 10EC5..10EC7, 10ED0..10ED8, 10EFA..10EFB
        Bengali (1 character): 09FF
        Han (5 characters): 16FF2..16FF6
        Kannada (1 character): 0CDC
        Latin (2 characters): A7D2, A7D4
        Oriya (2 characters): 0B53..0B54
        Phonetic (30 characters): 1ACF, 1AD0..1ADD, 1AE0..1AEB, A7CE..A7CF, A7F1
        Sharada (8 characters): 11B60..11B67
        Tangut (145 characters): 187F8..187FF, 18D09..18D1E, 18D80..18DF2
        Telugu (1 character): 0C5C
        Symbols (62 characters): 2B96, 1CCFA..1CCFC, 1CEBA..1CED0, 1CEE0..1CEF0, 1F777..1F77A, 1F8D0..1F8D8, 1FA54..1FA57, 1FBFA

### CODE REVIEW

**Comment by markusicu** [comment]
@eggrobin I changed the consensus number from C34 to C33. Apparently there is an off-by-one thing between your count and Rick's minutes.

**Review by asmusf — APPROVED** [review]

**Review by markusicu — COMMENTED** [review]
changes lgtm

Re Asmus’ concern: The new small circle with bar U+2B96 is mentioned in both the proposal and in https://github.com/unicode-org/sah/issues/323 as related to the larger U+29B5 which has gc=Sm.

**Review by markusicu — COMMENTED** [review]
name fix lgtm tnx

**Review by markusicu — COMMENTED** [review]
+1

**Review by markusicu — COMMENTED** [review]
code point move / new block look good

**Review by markusicu — APPROVED** [review]

**Comment by eggrobin** [comment]
> [markusicu](https://github.com/markusicu) approved these changes [now](https://github.com/unicode-org/unicodetools/pull/586#pullrequestreview-2440079933)
@[eggrobin](https://github.com/eggrobin) eggrobin requested a review from [markusicu](https://github.com/markusicu) [now](https://github.com/unicode-org/unicodetools/pull/586#event-15319936621)

I see you are rubberstamping these faster than I can ask you to!

**Pull request merged**
