### PR TITLE
Update ScriptExtensions.txt for Unicode 15.1

### PR DESCRIPTION
**Pull request by roozbehp**
* Add Sinh and Mlym to scx of U+1CF2
* Add Shrd to scx of U+A830..U+A835 and U+A838
* Sort scripts, first by count, and then alphabetically

This brings ScriptsExtensions.txt in sync with commit 67fa2d1bcb4dca1e8f296f1ffca59a3011718179 in https://github.com/roozbehp/unicode-data

### CODE REVIEW

**Comment by roozbehp** [comment]
This takes care of UTC Action Items 173-A115 and 173-A118.

**Comment by markusicu** [comment]
rslgtm -- @Ken-Whistler ok?

**Review by Ken-Whistler — APPROVED** [review]
Changes look fine.

**Comment by markusicu** [comment]
@Ken-Whistler please close UTC Action Items 173-A115 and 173-A118.

**Pull request merged**
