### PR TITLE
揚琴 slow 2..4

### PR DESCRIPTION
**Pull request by eggrobin**
See L2/24-071R, Proposal to encode three stable extended Suzhou Numeral–like letters for Cantonese Music, and the CJK report L2/24-067, Section 38).

See also
- PAG https://github.com/unicode-org/properties/issues/286
- RMG https://github.com/unicode-org/utc-release-management/issues/113

UTC-179-C44 Consensus: Accept the proposal to provisionally assign U+16FF4 YANGQIN SIGN SLOW TWO, U+16FF5 YANGQIN SIGN SLOW THREE, and U+16FF6 YANGQIN SIGN SLOW FOUR in the Ideographic Symbols and Punctuation block, based on document L2/24-071R2 (Chan) and Section 38 of document L2/24-067.

UTC-180-C14 Consensus: Change the name of the provisionally assigned characters U+16FF4, U+16FF5, and U+16FF6 from YANGQIN SIGN SLOW TWO, YANGQIN SIGN SLOW THREE, and YANGQIN SIGN SLOW FOUR to YANGQIN SIGN SLOW ONE BEAT, YANGQIN SIGN SLOW THREE HALF BEATS, and YANGQIN SIGN SLOW TWO BEATS.

[UTC-181-C60] Consensus: UTC accepts for encoding in Unicode 17.0 the following 297 Arabic, Bengali, Han, Kannada, Latin, Oriya, phonetic, Sharada, Tangut, Telugu, and symbol characters for which the code points have previously been provisionally assigned:
Arabic (40 characters): 088F, FBC3..FBD2, FD90..FD91, FDC8..FDCE, 10EC5..10EC7, 10ED0..10ED8, 10EFA..10EFB
Bengali (1 character): 09FF
Han (5 characters): 16FF2..16FF6
Kannada (1 character): 0CDC
Latin (2 characters): A7D2, A7D4
Oriya (2 characters): 0B53..0B54
Phonetic (30 characters): 1ACF, 1AD0..1ADD, 1AE0..1AEB, A7CE..A7CF, A7F1
Sharada (8 characters): 11B60..11B67
Tangut (145 characters): 187F8..187FF, 18D09..18D1E, 18D80..18DF2
Telugu (1 character): 0C5C
Symbols (62 characters): 2B96, 1CCFA..1CCFC, 1CEBA..1CED0, 1CEE0..1CEF0, 1F777..1F77A, 1F8D0..1F8D8, 1FA54..1FA57, 1FBFA

### CODE REVIEW

**Review by markusicu — COMMENTED** [review]
It looks like you need to either add these piecemeal to the `$NonOtherLetterIdeographs`, or else *define* that set as `[\p{Ideographic} - \p{gc=Lo}]` rather than testing that it's equal to that.

**Comment by eggrobin** [comment]
> It looks like you need to either add these piecemeal to the `$NonOtherLetterIdeographs`, or else define that set as `[\p{Ideographic} - \p{gc=Lo}]` rather than testing that it's equal to that.

I ended up doing both. It is a small enough set that there is some value, and not too much burden, in listing them.

**Review by markusicu — COMMENTED** [review]
lgtm

**Review by markusicu — COMMENTED** [review]
+½

**Pull request merged**
