### PR TITLE
Code points are no longer limited to 4 digits

### PR DESCRIPTION
**Pull request by nedley**
Fixes https://github.com/unicode-org/edcom/issues/80

### CODE REVIEW

**Review by markusicu — APPROVED** [review]

**Review by josh-hadley — APPROVED** [review]
👍

**Comment by nedley** [comment]
Paging @srl295…

**Comment by srl295** [comment]
@nedley if you mean the build failure, I kicked it, but you can merge without waiting for it if this isnt' a JSP affecting change.

**Comment by nedley** [comment]
bailey-dog-meme-2

**Pull request merged**
