### PR TITLE
in-file versions 16->17

### PR DESCRIPTION
**Pull request by markusicu**
and adjust in-file dates for files that have changed after 16

### CODE REVIEW

**Review by Ken-Whistler — APPROVED** [review]
I'm fine with all these changes, but is there a reason some of the Date lines are updated, and some are not?

**Comment by markusicu** [comment]
> I'm fine with all these changes, but is there a reason some of the Date lines are updated, and some are not?

Yes.
I updated the ones that had updated contents, matching the dates when they changed in the repo.
I left the dates alone in files that had no contents changes since Unicode 16.

**Comment by markusicu** [comment]
... and I suspect that some of these files will want a review for new characters in 17, for example BidiMirroring.txt.

**Comment by markusicu** [comment]
i had to remove StandardizedVariants.txt from this PR...

**Review by eggrobin — APPROVED** [review]

**Pull request merged**
