### PR TITLE
Add Katakana middle dots to OIDC, and thence to IDC & XIDC.

### PR DESCRIPTION
**Pull request by eggrobin**
UTC-176-C18 Consensus: Add the characters U+30FB KATAKANA MIDDLE DOT and U+FF65 HALFWIDTH KATAKANA MIDDLE DOT to Other_ID_Continue and its derivative properties, as described in L2/23-160 item 2.2, for Unicode Version 15.1.

UTC-176-A64 Action Item for Robin Leroy, PAG: Add the characters U+30FB KATAKANA MIDDLE DOT and U+FF65 HALFWIDTH KATAKANA MIDDLE DOT to Other_ID_Continue and its derivative properties, as described in L2/23-160 item 2.2, for Unicode Version 15.1

### CODE REVIEW

**Review by macchiati — DISMISSED** [review]

**Review by markusicu — DISMISSED** [review]
lgtm very nice
too bad it merge-conflicts with PR #513

**Comment by eggrobin** [comment]
> too bad it merge-conflicts with PR https://github.com/unicode-org/unicodetools/pull/513

Feel free to merge first, I have conflict resolution commands ready to paste in my shell.

**Comment by markusicu** [comment]
> Feel free to merge first,

done tnx

> I have conflict resolution commands ready to paste in my shell.

your turn

**Review by markusicu — APPROVED** [review]
lgtm tnx please squash-n-merge

**Pull request merged**
