### PR TITLE
ucdxml 15.0 tests

### PR DESCRIPTION
**Pull request by macchiati**

### CODE REVIEW

**Comment by macchiati** [comment]
I don't expect a close review; captured problems in issue https://github.com/unicode-org/unicodetools/issues/325

**Comment by macchiati** [comment]
Converting to draft until I can run spotless.

**Comment by markusicu** [comment]
Aside from the formatter complaints, there is also a unit test failure:
```
Check if GenerateEnums output has been committed to repo
git diff --compact-summary
 .../java/org/unicode/props/UcdPropertyValues.java  |   3 +-
 .../org/unicode/propstest/CheckXmlProperties.java  |  47 ++--
 .../java/org/unicode/propstest/XMLProperties.java  | 276 ++++++++++-----------
 3 files changed, 170 insertions(+), 156 deletions(-)
git diff --name-status | awk '{print ;}'
Failure: GenerateEnums has changes that need to be committed.
```

**Comment by markusicu** [comment]
Mark: I noticed that [your repo fork](https://github.com/macchiati/unicodetools) is very out of date. I assume that this PR is not based on that (or else it should show more discrepancies), but you might want to update your fork.

Note that this has gotten very easy: Go to your fork URL, and above the file list you will see a refresh icon with "Sync fork". Click that, and then "Update branch".

**Comment by markusicu** [comment]
I only glanced at the code changes (large diffs partly due to formatting). What I see looks plausible...

**Comment by macchiati** [comment]
I haven't actually been using the fork lately...

**Comment by markusicu** [comment]
> I haven't actually been using the fork lately...

This dev branch does live in your fork (as usual).

And I assume that your dev branch is based on a current version of the upstream main branch, or else the XML check would have found the ucdxml data to be inconsistent with the normal data.

How do you create a branch in your fork from a current version of the upstream main branch without keeping your fork up to date? AFAIK normally one updates the fork, pulls main from there into the workspace, and then creates a branch there.

**Review by markusicu — APPROVED** [review]
lgtm

The PR is still "draft" but looks plausible, and the tests pass.

It seems like the overall changes are smaller after the reformatting. Maybe your IDE is set to format differently from the Android style?

**Comment by macchiati** [comment]
The format is whatever Eclipse settings produce (from CLDR), but I think we
are going to move to spotless and in addition try to change the Eclipse
settings to be close to that.

**Comment by markusicu** [comment]
> The format is whatever Eclipse settings produce (from CLDR), but I think we are going to move to spotless and in addition try to change the Eclipse settings to be close to that.

We did move to google-java-format, enforced via spotless.
If you follow [our setup instructions](https://github.com/unicode-org/unicodetools/blob/main/docs/build.md#source-code-formatting), then your Eclipse should do less battle with spotless.
> Eclipse: Follow the [instructions](https://source.android.com/devices/tech/test_infra/tradefed/development/eclipse#auto_format) in the "Auto format" section. You can alternatively use this link for [android-formatting.xml](https://raw.githubusercontent.com/aosp-mirror/platform_development/master/ide/eclipse/android-formatting.xml).

I believe I downloaded the .xml file from that latter link and pointed Eclipse to it according to the instructions.

What was especially jarring for me was imports reordering. I ended up telling Eclipse not to reorder them when saving files.

**Comment by markusicu** [comment]
> lgtm
> 
> The PR is still "draft" but looks plausible, and the tests pass.

@macchiati ready to move this out of draft, and merge?

**Comment by macchiati** [comment]
Yup, thanks

**Comment by markusicu** [comment]
... and please merge if you are done.

**Pull request merged**
