### PR TITLE
Emoji 14.0 data

### PR DESCRIPTION
**Pull request by nedley**
WIP, some hacking still needed to show correct proposal data (especially for handshake).

### CODE REVIEW

**Review by macchiati — DISMISSED** [review]
There are some spurious format differences from the baseline. 
Also, there should be differences from the emoji-zwj-sequences.txt file.

However, I'm approving this anyway, since it will then be easier to diff, and add the emoji-zwj-sequences.txt afterwards.

**Comment by macchiati** [comment]
Once it is merged, I'll do a more comprehensive review of the data files.

**Comment by nedley** [comment]
The changes you seek are in my `/emoji/docs/Public/emoji/14.0`, I can copy those to `/unicodetools/unicodetools/data/emoji/14.0` now…

**Comment by macchiati** [comment]
Hi, I sync'ed to your emoji 14 branch, then loaded in the Public (released)
files into 13.1 for comparison. Checked in as a branch to yours.

I could then do a reasonable diff between 13.1 and your 14.0.

I count now 37 new characters, so missing are still the zwj and emoji
modifier sequences.

Mark

**Comment by macchiati** [comment]
That is, looking at
https://unicode.org/emoji/future/emoji-candidates.html#emoji_counts, we
should be seeing 55 new entries in the emoji-sequences.txt file, (aside
from Basic, which will also grow), and 20 new entries in the
emoji-zwj-sequences.txt file.

Mark

**Comment by macchiati** [comment]
I will have some time tomorrow if you want to team program a bit.

Mark

**Comment by nedley** [comment]
> That is, looking at https://unicode.org/emoji/future/emoji-candidates.html#emoji_counts, we should be seeing 55 new entries in the emoji-sequences.txt file, (aside from Basic, which will also grow), and 20 new entries in the emoji-zwj-sequences.txt file.

I am seeing exactly that in my local changes. Unless you object, I will add `unicodetools/data/emoji/14.0` to the PR.

**Comment by macchiati** [comment]
Yes, please do.

**Comment by macchiati** [comment]
Let me know when you've added it.

Mark

**Review by macchiati — APPROVED** [review]

**Comment by macchiati** [comment]
I went ahead and merged this.

**Pull request merged**
