### PR TITLE
Add more tests for regex BNF

### PR DESCRIPTION
**Pull request by macchiati**
Add more code to test the UTS #18 EBNF

### CODE REVIEW

**Comment by macchiati** [comment]
Adds some files that do parsing at a higher level (not as optimized as UnicodeSet) to make it easier to make changes. Use it to test proposed UTS #18 EBNF updates.

**Comment by markusicu** [comment]
Is this still relevant? Should I assign this to myself for review?

I think I looked at this some time ago and had some concerns about duplicating code from ICU class UnicodeSet... or was that a different discussion?

**Comment by markusicu** [comment]
@macchiati reminder of an old project...

**Comment by markusicu** [comment]
Hi @macchiati it looks like there are two sets of changes here:
- Some changes in emoji-proposal-handling code, adding some extra checks?
- An additional UnicodeSet parser related to the TC39 ECMAScript regex proposal?

Are you intending to take one or both of these into the main branch eventually?

@nedley FYI something to grab from the emoji code changes here?

**Comment by macchiati** [comment]
This was during investigations of regex sets of strings. I'll close it.

**Pull request closed without merging**
