### PR TITLE
Test consistency of grapheme cluster segmentation with canonical equivalence some more

### PR DESCRIPTION
**Pull request by eggrobin**
… and fix it.

UTC-180-CXXX Consensus: Assign the Other_Grapheme_Extend property to U+0CC0, U+0CC7, U+0CC8, and U+0CCA, U+0CCB (Kannada vowel signs II, EE, AI, O, and OO), as well as U+1B3B, U+1B3D, and U+1B43 (Balinese vowel signs ra repa tedung, la lenga tedung, and pepet tedung), thereby changing their Grapheme_Cluster_Break property from SpacingMark to Extend, ensuring consistency of legacy grapheme clusters with canonical equivalence. For Unicode 16.0. See L2/24-162 item 6.2, PRI-494#ID20240422114157, and PRI-494#ID20240422120150.

See https://github.com/unicode-org/properties/issues/287.

Previously: https://github.com/unicode-org/unicodetools/pull/645.

### CODE REVIEW

**Review by macchiati — DISMISSED** [review]
LGTM Might want to wait for props meeting, in case anyone has qualms.

**Comment by eggrobin** [comment]
> Might want to wait for props meeting, in case anyone has qualms.

Might want to wait for UTC, since it is a change to the property assignments of existing characters!

**Comment by macchiati** [comment]
dooooh ... even better

**Comment by markusicu** [comment]
[Test still fails](https://github.com/unicode-org/unicodetools/actions/runs/9306404434/job/25615536912?pr=839):
```
[INFO] Running org.unicode.text.UCD.TestTestUnicodeInvariants
Error: Got unexpected property values: 1
0CCB          ; Extend≠SpacingMark #      (ೋ)  KANNADA VOWEL SIGN OO
```

**Comment by eggrobin** [comment]
> Test still fails

I know, I commented on that on the PAG issue. Will fix it here.

**Review by markusicu — COMMENTED** [review]
lgtm

**Review by macchiati — APPROVED** [review]

**Pull request merged**
