### PR TITLE
UCD 15.0 updates

### PR DESCRIPTION
**Pull request by Manishearth**
### Ken Feb 2

Markus,

Updated in the alpha directory:

https://www.unicode.org/Public/15.0.0/ucd/NamesList-15.0.0d2.txt

This reflects some required edits for 4 Kazakh digraphs, based on
Michel's disposition of comments for the CDAM.

### CODE REVIEW

**Comment by markusicu** [comment]
lgtm

About the files where only the timestamps and copyright years change: I would probably not have checked those in. But it's ok, too, and eventually we will want 2022 copyrights for Unicode 15 data files anyway. @Ken-Whistler what do you think?

**Comment by Manishearth** [comment]
Yeah the tool decided they had changed so I included them

**Comment by Ken-Whistler** [comment]
I would not check them in, either. I treat updates like those as null operations for my own manual tracking. But then how I've been managing deltas no longer matches how you guys are handling repository checkins.

**Comment by Manishearth** [comment]
This works!

**Comment by Manishearth** [comment]
Can we still merge this for the NamesList update? Can remove the second commit if people want

**Comment by Ken-Whistler** [comment]
I was just indicating what I would do. I don't have much visibility on how this looks form the inside of unicodetools. So do whatever makes the most sense to you.

**Comment by Manishearth** [comment]
@markusicu r?

**Review by markusicu — APPROVED** [review]
lgtm tnx
please *squash-and-merge*

**Pull request merged**
