### PR TITLE
Don’t strip controls in input fields

### LINKED ISSUE #352: toHTML is overzealous for input fields
Example: in https://util.unicode.org/UnicodeJsps/bidi.jsp, clear the text field, press `RLE`, type `123 456`; the text field reads:  
`‫123 456`‬
Press `Show Bidi`. [The text field now reads `123 456`, while showing what was happening in the `‫123 456`‬](https://util.unicode.org/UnicodeJsps/bidi.jsp?a=%E2%80%AB123+456&p=Auto); pressing `Show Bidi` again will show the (boring) application of the UBA to `123 456`. This is confusing and obnoxious when experimenting with the UBA.

In input fields (as opposed to tables etc.), we should only be applying the `BASE_RULES`, `CONTENT_RULES`, and `HTML_RULES`, not the controls rules; if someone types in some funny controls, we don’t want to strip them whenever a button is pressed.

### PR DESCRIPTION
**Pull request by eggrobin**
Fix #352.

### CODE REVIEW

**Review by echeran — APPROVED** [review]
LGTM, but deferring to the review from others.  IIUC, the salient commit here is https://github.com/unicode-org/unicodetools/pull/353/commits/f594a96a3c224a5a5d20ebcbf107acebd4531084, which constructs the less aggressive transiliterator rule set to apply to the input box.  The other commits exist only because this PR is branched from (was created on top of) the other PR.

**Comment by markusicu** [comment]
nice!

please squash/rebase for linear history on `main`.

**Comment by eggrobin** [comment]
> please squash/rebase for linear history on main.

`Squash and merge` will do that, right?

**Comment by markusicu** [comment]
> > please squash/rebase for linear history on main.
> 
> `Squash and merge` will do that, right?

I think it should... maybe my mistake was to review your changes one commit at a time. Now looking at "changes from all commits" it looks ok. Please do remember to squash when you merge.

**Review by markusicu — APPROVED** [review]
lgtm tnx, pse *squash*-and-merge

**Pull request merged**
