### PR TITLE
Dockerize

### PR DESCRIPTION
**Pull request by srl295**
- rebased on current!
- add action to build docker image (does not deploy anywhere)
- [x] TODO: need to support `$PORT`

### CODE REVIEW

**Comment by srl295** [comment]
I think this is ready to merge. It at least verifies that the JSPs can build, even if it's not ready to deploy to GCP yet.

**Comment by srl295** [comment]
it now supports PORT. So, we need to figure out how to get the image pushed and it's ready to go.

**Comment by macchiati** [comment]
This is pretty much greek to me, so my review won't add any value...

**Comment by srl295** [comment]
pushing to https://hub.docker.com/repository/docker/unicode/unicode-jsp

**Comment by srl295** [comment]
specifically `unicode/unicode-jsp:pr9`

**Pull request merged**
