### PR TITLE
jsp: Update JSPs to 15.1.0

### PR DESCRIPTION
**Pull request by srl295**
Fixes: #556
Fixes: #573 - C Bidi reference

Also bumps CLDR to v44 beta

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Comment by markusicu** [comment]
Wait, there is a JSP test failure:
```
Error:  Failures: 
Error:    TestJsp>TestFmwkMinusMinus.tearDown:23 errln()
: expected matches /invalid\sextlang\scode/ ==> expected: <0> but was: <1>
Error:    TestLanguageid.TestParse:14->TestFmwkMinusMinus.assertTrue:70 expected: <true> but was: <false>
[INFO] 
Error:  Tests run: 148, Failures: 2, Errors: 0, Skipped: 48
```

**Comment by srl295** [comment]
> Wait, there is a JSP test failure:
> 
> ```
> Error:  Failures: 
> Error:    TestJsp>TestFmwkMinusMinus.tearDown:23 errln()
> : expected matches /invalid\sextlang\scode/ ==> expected: <0> but was: <1>
> Error:    TestLanguageid.TestParse:14->TestFmwkMinusMinus.assertTrue:70 expected: <true> but was: <false>
> [INFO] 
> Error:  Tests run: 148, Failures: 2, Errors: 0, Skipped: 48
> ```

Yeah, what does it mean?

```
ava.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.IllegalArgumentException: Failures:
	FBC2	Nd	U+116D0 MYANMAR PAO DIGIT ZERO
	FBC2	Nd	U+116D1 MYANMAR PAO DIGIT ONE
	FBC2	Nd	U+116D2 MYANMAR PAO DIGIT TWO
	FBC2	Nd	U+116D3 MYANMAR PAO DIGIT THREE
	FBC2	Nd	U+116D4 MYANMAR PAO DIGIT FOUR
	FBC2	Nd	U+116D5 MYANMAR PAO DIGIT FIVE
	FBC2	Nd	U+116D6 MYANMAR PAO DIGIT SIX
	FBC2	Nd	U+116D7 MYANMAR PAO DIGIT SEVEN
	FBC2	Nd	U+116D8 MYANMAR PAO DIGIT EIGHT
	FBC2	Nd	U+116D9 MYANMAR PAO DIGIT NINE
	FBC2	Nd	U+116DA MYANMAR EASTERN PWO KAREN DIGIT ZERO
	FBC2	Nd	U+116DB MYANMAR EASTERN PWO KAREN DIGIT ONE
	FBC2	Nd	U+116DC MYANMAR EASTERN PWO KAREN DIGIT TWO
	FBC2	Nd	U+116DD MYANMAR EASTERN PWO KAREN DIGIT THREE
	FBC2	Nd	U+116DE MYANMAR EASTERN PWO KAREN DIGIT FOUR
	FBC2	Nd	U+116DF MYANMAR EASTERN PWO KAREN DIGIT FIVE
	FBC2	Nd	U+116E0 MYANMAR EASTERN PWO KAREN DIGIT SIX
	FBC2	Nd	U+116E1 MYANMAR EASTERN PWO KAREN DIGIT SEVEN
	FBC2	Nd	U+116E2 MYANMAR EASTERN PWO KAREN DIGIT EIGHT
	FBC2	Nd	U+116E3 MYANMAR EASTERN PWO KAREN DIGIT NINE
	FBC2	Po	U+11BE1 SUNUWAR SIGN PVO
	FBC2	Nd	U+11BF0 SUNUWAR DIGIT ZERO
	FBC2	Nd	U+11BF1 SUNUWAR DIGIT ONE
	FBC2	Nd	U+11BF2 SUNUWAR DIGIT TWO
	FBC2	Nd	U+11BF3 SUNUWAR DIGIT THREE

    at org.unicode.text.UCA.WriteCollationData.buildCldrCollator (WriteCollationData.java:2173)
    at org.unicode.text.UCA.WriteCollationData.getCollator (WriteCollationData.java:1867)
    at org.unicode.text.UCA.WriteAllkeys.writeAllkeys (WriteAllkeys.java:48)
    at org.unicode.text.UCA.Main.main (Main.java:141)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:293)
    at java.lang.Thread.run (Thread.java:829)
```

i'm guessing this isn't Unicode 15.1 stuff…

**Comment by srl295** [comment]
@markusicu it started failing when https://github.com/unicode-org/unicodetools/pull/375 was merged. It's not blocking apparently.

**Comment by srl295** [comment]
@markusicu how does the staged JSP  look if it's OK i'll push it to production

**Comment by markusicu** [comment]
Please ignore the “Check UCA data” failure. That will fail for a while during Unicode 16 work.

[The other CI failure](https://github.com/unicode-org/unicodetools/actions/runs/6565515067/job/17834198695?pr=577) is new I believe. It's in org.unicode.jsptest.TestJsp.TestLanguageTag so that seems relevant.

Otherwise the changes look fine.

**Comment by srl295** [comment]
ah ok, i'll look into it then

**Comment by srl295** [comment]
jsp failures actually were data not updated properly (the update must have cancelled).  Took me a while to debug the tests, but the JSP ones are now passing.

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Pull request merged**
