### PR TITLE
update tomcat version to 9.0.37

### PR DESCRIPTION
**Pull request by srl295**
Update to #9

### CODE REVIEW

**Comment by mihnita** [comment]
BTW, my approval might not mean much.
I think my Github account is worth nothing for the Unicode (and Google) groups :-)

**Comment by srl295** [comment]
@macchiati @sffc markusicu mihai has okayed this, can i get a rubber stamp? You can see that the build passes now.

**Comment by macchiati** [comment]
At this point, let's wait until a couple hours after the push to
production, just on the off chance that it destabilizes something. That
should be before noon tomorrow, since Tom is on ET.

Mark

**Comment by srl295** [comment]
We can, but this isn’t CLDR :)

**Comment by macchiati** [comment]
whoops!
Mark

**Comment by macchiati** [comment]
Approved.

Mark

**Pull request merged**
