### PR TITLE
deps: use prerelease CLDR 42 dev tag

### PR DESCRIPTION
**Pull request by srl295**
For: #218
Followon to: #224

- to pickup JDK11 fixes
- Also, dropped some unneeded lines from pom.xml (duplicate version and groupId fields) to fix warnings
- This is CLDR `0.0.0-SNAPSHOT-e849e51d51` corresponding to [`snapshot/2022-04-25`](https://github.com/unicode-org/cldr/releases/tag/snapshot%2F2022-04-25)

- Also checkin some .settings files that eclipse seems to want to modify

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm tnx!

please *squash*-and-merge as usual

**Comment by markusicu** [comment]
Hm, now I get "Missing artifact org.unicode.cldr:cldr-code:jar:0.0.0-SNAPSHOT-e849e51d51" :-(

```
org.unicode.cldr:cldr-code:jar:0.0.0-SNAPSHOT-e849e51d51 failed to transfer from https://maven.pkg.github.com/unicode-org/cldr during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of githubcldr has elapsed or updates are forced. Original error: Could not transfer artifact org.unicode.cldr:cldr-code:jar:0.0.0-SNAPSHOT-e849e51d51 from/to githubcldr (https://maven.pkg.github.com/unicode-org/cldr): The operation was cancelled.

org.eclipse.aether.transfer.ArtifactTransferException: org.unicode.cldr:cldr-code:jar:0.0.0-SNAPSHOT-e849e51d51 failed to transfer from https://maven.pkg.github.com/unicode-org/cldr during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of githubcldr has elapsed or updates are forced. Original error: Could not transfer artifact org.unicode.cldr:cldr-code:jar:0.0.0-SNAPSHOT-e849e51d51 from/to githubcldr (https://maven.pkg.github.com/unicode-org/cldr): The operation was cancelled.
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:225)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:189)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:574)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:484)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:402)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:191)
	at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:227)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:200)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:124)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:649)
	at org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:65)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:535)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$3(ProjectRegistryManager.java:499)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:156)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:497)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:349)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:303)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:413)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$1(ProjectConfigurationManager.java:362)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:182)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:156)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:103)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1411)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:361)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:42)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by markusicu** [comment]
The version hash should work... https://github.com/unicode-org/cldr/packages/521051

**Comment by srl295** [comment]
try `mvn compile -U`  from the command line  which will tell it to retry. Maybe it was not available everywhere on the server? or hadn’t propagated?

**Comment by markusicu** [comment]
That command was successful, and Eclipse seems happy now.
Thanks again!

**Comment by echeran** [comment]
Yep, the fix here to bump the version to the latest worked for me, too. Thanks!

**Pull request merged**
