### PR TITLE
Kawi sign nukta

### PR DESCRIPTION
**Pull request by eggrobin**
[[173-C28](https://www.unicode.org/cgi-bin/GetL2Ref.pl?173-C28)] Consensus: Accept U+11F5A KAWI SIGN NUKTA, with name, glyph, and properties as given in [L2/22-236](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/22-236) for a future version of the Unicode Standard. (Ref. section 8 of [L2/22-248](https://www.unicode.org/cgi-bin/GetMatchingDocs.pl?L2/22-248))

Checked consistency with Ken’s UnicodeData (draft 8) and LineBreak (draft 3).

### CODE REVIEW

**Review by roozbehp — DISMISSED** [review]
LGTM

**Comment by roozbehp** [comment]
If Nukta⟹Diacritic, perhaps add an invariant?

**Comment by eggrobin** [comment]
> If Nukta⟹Diacritic, perhaps add an invariant?

Yes, but we will need to change the assignment for those nuktas that are not called nuktas; I added that to https://github.com/unicode-org/properties/issues/195#issuecomment-1804962555.

**Comment by roozbehp** [comment]
> Yes, but we will need to change the assignment for those nuktas that are not called nuktas; I added that to [unicode-org/properties#195 (comment)](https://github.com/unicode-org/properties/issues/195#issuecomment-1804962555).

Can't you add temporary exceptions?

**Comment by markusicu** [comment]
@echeran reminder, you are the assignee = voluntold main reviewer :-)

**Comment by eggrobin** [comment]
> Can't you add temporary exceptions?

Done.

**Review by roozbehp — APPROVED** [review]
LGTM

**Pull request merged**
