### PR TITLE
fix invariants of lb=SA and of GCB=SpacingMark exceptions

### PR DESCRIPTION
**Pull request by markusicu**
Fixes issue #220
Fixes issue #221
Fixes issue #222

### CODE REVIEW

**Comment by markusicu** [comment]
@NorbertLindenberg FYI (GitHub does not let me add you to the list of reviewers)

**Review by Ken-Whistler — COMMENTED** [review]
Generally this looks good, but I am not competent to comment on the details of the construction of the invariant tests.

**Comment by markusicu** [comment]
@Ken-Whistler most of this pull request is in changing explanatory text. Would you mind approving it based on that, assuming the text looks ok?

**Comment by NorbertLindenberg** [comment]
[ToolUnicodePropertySource.java](https://github.com/unicode-org/unicodetools/pull/230#diff-29e6d97f62bf888d7f8351b49a76b6e27835fe56a911f9702d52e849bc95aabe):

* Line 834 still lists Kawi characters.
* Is it still necessary to list the New Tai Lue characters?
* Is the version test for Ahom in line 836 still needed?

[UnicodeInvariantTest.txt](https://github.com/unicode-org/unicodetools/pull/230#diff-c2f2f053bbaa14f43053e3fb81a8afd67add46a4be1377d3e411f0500b40dabf)

* There's still too much emphasis on spaces. In Asia at least, the presence or absence of spaces is not a good predictor for line-breaking behavior. Tibetan uses spaces, but doesn't break lines at them; it has other characters that provide line breaking opportunities. Grantha nowadays uses spaces, but also breaks at orthographic syllable boundaries. Chinese doesn't use spaces, but allows breaks almost anywhere. Thai uses spaces for phrases, but breaks at word boundaries, which are not marked in any way.
* Grantha is not a south east Asian script.
* It doesn't seem necessary to discuss what scripts do that don't fall into the SA bucket.
* I'd replace lines 466-481 with:

> A few southeast Asian scripts allow line breaks only at word boundaries, but do not mark word boundaries in any way, so that the determination of line break opportunities requires language dependent text analysis. In terms of UAX #14, these scripts need the “South East Asian” style of context analysis for line breaking, and their characters are given lb=SA (Line_Break=SA: complex context dependent) as an escape out of the rule-based algorithm in UAX #14.
>
> For these scripts, test the following invariant:

**Comment by Ken-Whistler** [comment]
Yeah, see what Norbert wrote. Again, I say, I'm not really competent to judge the invariant tests here, or even the description of what they are trying to do. If you need an approval to commit this, ask somebody else.

**Comment by markusicu** [comment]
> ToolUnicodePropertySource.java:
> 
> * Line 834 still lists Kawi characters.

I removed them in a separate PR that is merged already: https://github.com/unicode-org/unicodetools/pull/229

> * Is it still necessary to list the New Tai Lue characters?

Unsure; I already added a note about them.
This code looks like it wants to compute different results for different Unicode versions, and I don't want to change anything that might change results for older versions. It would be tedious to test.
I also don't want to make unrelated changes.

> * Is the version test for Ahom in line 836 still needed?

Presumably yes. The data changed for Unicode 14, so we need the version test in order to generate different data for 13 and before.

> UnicodeInvariantTest.txt
> 
> * There's still too much emphasis on spaces. In Asia at least, the presence or absence of spaces is not a good predictor for line-breaking behavior. Tibetan uses spaces, but doesn't break lines at them; it has other characters that provide line breaking opportunities. Grantha nowadays uses spaces, but also breaks at orthographic syllable boundaries. Chinese doesn't use spaces, but allows breaks almost anywhere. Thai uses spaces for phrases, but breaks at word boundaries, which are not marked in any way.
> * Grantha is not a south east Asian script.
> * It doesn't seem necessary to discuss what scripts do that don't fall into the SA bucket.
> * I'd replace lines 466-481 with: [...]

sgtm, thanks, done.

@NorbertLindenberg PTAL

**Review by echeran — APPROVED** [review]
RSLGTM

**Comment by NorbertLindenberg** [comment]
Looks good to me.

**Review by Manishearth — APPROVED** [review]

**Pull request merged**
