### PR TITLE
UCA 16.0 from Ken

### PR DESCRIPTION
**Pull request by markusicu**
Successive changes from Ken for adding new characters to the default sort order.
Files from Ken taken verbatim; commit messages quoting Ken's progress notes (notes per delta from Ken's UCA16Journal.txt in each corresponding commit).

### CODE REVIEW

**Review by macchiati — APPROVED** [review]
Spot-checking commits. Looks good so far.

**Comment by eggrobin** [comment]
(Closing and reopening to rerun CI.)

**Comment by markusicu** [comment]
Ken has sent more updates to the data and to the sifter code. I will try to catch up with those “soon”.

**Comment by markusicu** [comment]
I have caught up with Ken's recent changes, and I am taking this out of draft for review and merging. I will look into the UCA test failure separately; at a minimum, I will need to hardcode sample characters for future scripts.

**Review by Ken-Whistler — APPROVED** [review]
Changes look like they have caught up o.k.

**Pull request merged**
